### ISSUE TITLE
Added Functionality to ADAudit.xml

### ISSUE THREAD

**Issue by ghost** [bakhterets/Zabbix-templates-for-Active-Directory#2]
Hi Sir,

I've added additional steps to your ADAudit.xml and formatted without yell descriptions.

Hope you like it,

Kind regards,
Martijn Kamminga

Security Event Log 1102 - Security Event Log was cleared
System Event Log 7045 - New Service creation event
Security Event Log 4720 - New local user created
Scheduled Task Operational Log 106/200 - Scheduled Task was registered or executed

Existed 4624 - Successful Logon - logon type 4.  This type of logon leaves credentials exposed in the LSA.
Existed 4625 - Unsuccessful Logon

4648 - Logon was Attempted with Explicit Credentials
4964 - Special groups have been assigned to a new logon
4672 - Special privileges assigned to new logon
4769 - A Kerberos service ticket was requested

[ADAudit.xml.txt](https://github.com/bakhterets/Zabbix-templates-for-Active-Directory/files/3048198/ADAudit.xml.txt)

**Comment by bakhterets** [comment]
> Hi Sir,
> 
> I've added additional steps to your ADAudit.xml and formatted without yell descriptions.
> 
> Hope you like it,
> 
> Kind regards,
> Martijn Kamminga
> 
> Security Event Log 1102 - Security Event Log was cleared
> System Event Log 7045 - New Service creation event
> Security Event Log 4720 - New local user created
> Scheduled Task Operational Log 106/200 - Scheduled Task was registered or executed
> 
> Existed 4624 - Successful Logon - logon type 4. This type of logon leaves credentials exposed in the LSA.
> Existed 4625 - Unsuccessful Logon
> 
> 4648 - Logon was Attempted with Explicit Credentials
> 4964 - Special groups have been assigned to a new logon
> 4672 - Special privileges assigned to new logon
> 4769 - A Kerberos service ticket was requested
> 
> [ADAudit.xml.txt](https://github.com/bakhterets/Zabbix-templates-for-Active-Directory/files/3048198/ADAudit.xml.txt)

Audit log monitoring functionality is not particularly needed in a work environment. To do this, it is better to use elasticsearch.
