### ISSUE TITLE
replication on W2008r2

### ISSUE THREAD

**Issue by hubertsvk** [bakhterets/Zabbix-templates-for-Active-Directory#3]
PS C:\Windows\system32> Get-ADReplicationPartnerMetadata
Get-ADReplicationPartnerMetadata : The term 'Get-ADReplicationPartnerMetadata' is not recognized as the name of a cmdlet
r if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-ADReplicationPartnerMetadata

**Comment by bakhterets** [comment]
> PS C:\Windows\system32> Get-ADReplicationPartnerMetadata
> Get-ADReplicationPartnerMetadata : The term 'Get-ADReplicationPartnerMetadata' is not recognized as the name of a cmdlet
> r if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> 
> * Get-ADReplicationPartnerMetadata

This cmdlet needs the ActiveDirectory module which is on any DC in domain.

**Comment by olegkaspersky** [comment]
> > PS C:\Windows\system32> Get-ADReplicationPartnerMetadata
> > Get-ADReplicationPartnerMetadata : The term 'Get-ADReplicationPartnerMetadata' is not recognized as the name of a cmdlet
> > r if a path was included, verify that the path is correct and try again.
> > At line:1 char:1
> > 
> > * Get-ADReplicationPartnerMetadata
> 
> This cmdlet needs the ActiveDirectory module which is on any DC in domain.

It doesn't work with AD module installed
